GET http://localhost:3020/

###

POST http://localhost:3020/

###

GET http://localhost:3020/confused

###

GET http://localhost:3020/content

###

POST http://localhost:3020/sad

###

POST http://localhost:3020/happy
